export const UPDATE_NAME_INPUT = "UPDATE_NAME_INPUT";
export const UPDATE_VERSION_INPUT = "UPDATE_VERSION_INPUT";
export const FORMS = {
    LOAD: 'FORMS_LOAD',
    LOAD_SUCCESS: 'FORMS_LOAD_SUCCESS',
    LOAD_FAIL: 'FORMS_LOAD_FAIL',
};

export const SCHEMAS = {
    LOAD: 'SCHEMAS_LOAD',
    LOAD_SUCCESS: 'SCHEMAS_LOAD_SUCCESS',
    LOAD_FAIL: 'SCHEMAS_LOAD_FAIL',
};

export const DATARECORDS = {
    LOAD: 'DATARECORDS_LOAD',
    LOAD_SUCCESS: 'DATARECORDS_LOAD_SUCCESS',
    LOAD_FAIL: 'DATARECORDS_LOAD_FAIL',
};

export const ONEFORM = {
    LOAD: 'FORM_LOAD',
    LOAD_SUCCESS: 'FORM_LOAD_SUCCESS',
    LOAD_FAIL: 'FORM_LOAD_FAIL',
    DELETE_SUCCESS: 'FORM_DELETE_SUCCESS',
    UPDATE_SUCCESS: 'FORM_UPDATE_SUCCESS',
    CREATE_SUCCESS: 'FORM_CREATE_SUCCESS',
    DELETE_FAIL: 'FORM_DELETE_FAIL',
    UPDATE_FAIL: 'FORM_UPDATE_FAIL',
    CREATE_FAIL: 'FORM_CREATE_FAIL',
    CREATE: "FORM_CREATE",
    UPDATE: "FORM_UPDATE",
    DELETE: "FORM_DELETE",
    RESET: "FORM_RESET",
};

export const ONESCHEMA = {
    LOAD: 'SCHEMA_LOAD',
    LOAD_SUCCESS: 'SCHEMA_LOAD_SUCCESS',
    LOAD_FAIL: 'SCHEMA_LOAD_FAIL',
    DELETE_SUCCESS: 'SCHEMA_DELETE_SUCCESS',
    UPDATE_SUCCESS: 'SCHEMA_UPDATE_SUCCESS',
    CREATE_SUCCESS: 'SCHEMA_CREATE_SUCCESS',
    DELETE_FAIL: 'SCHEMA_DELETE_FAIL',
    UPDATE_FAIL: 'SCHEMA_UPDATE_FAIL',
    CREATE_FAIL: 'SCHEMA_CREATE_FAIL',
    CREATE: "SCHEMA_CREATE",
    UPDATE: "SCHEMA_UPDATE",
    DELETE: "SCHEMA_DELETE",
    RESET: "SCHEMA_RESET",
};


export const ONEDATARECORD = {
    LOAD: 'DATARECORD_LOAD',
    LOAD_SUCCESS: 'DATARECORD_LOAD_SUCCESS',
    LOAD_FAIL: 'DATARECORD_LOAD_FAIL',
    DELETE_SUCCESS: 'DATARECORD_DELETE_SUCCESS',
    UPDATE_SUCCESS: 'DATARECORD_UPDATE_SUCCESS',
    CREATE_SUCCESS: 'DATARECORD_CREATE_SUCCESS',
    DELETE_FAIL: 'DATARECORD_DELETE_FAIL',
    UPDATE_FAIL: 'DATARECORD_UPDATE_FAIL',
    CREATE_FAIL: 'DATARECORD_CREATE_FAIL',
    CREATE: "DATARECORD_CREATE",
    UPDATE: "DATARECORD_UPDATE",
    DELETE: "DATARECORD_DELETE",
    RESET: "DATARECORD_RESET",
};