export const FORMS = {
    LOAD: 'FORMS_LOAD',
    LOAD_SUCCESS: 'FORMS_LOAD_SUCCESS',
    LOAD_FAIL: 'FORMS_LOAD_FAIL',
};

export const ONEFORM = {
    LOAD: 'FORM_LOAD',
    LOAD_SUCCESS: 'FORM_LOAD_SUCCESS',
    LOAD_FAIL: 'FORM_LOAD_FAIL',
    DELETE_SUCCESS: 'FORM_DELETE_SUCCESS',
    UPDATE_SUCCESS: 'FORM_UPDATE_SUCCESS',
    CREATE_SUCCESS: 'FORM_CREATE_SUCCESS',
    DELETE_FAIL: 'FORM_DELETE_FAIL',
    UPDATE_FAIL: 'FORM_UPDATE_FAIL',
    CREATE_FAIL: 'FORM_CREATE_FAIL',
    CREATE: "CREATE_FORM",
    UPDATE: "UPDATE_FORM",
    DELETE: "DELETE_FORM",
    RESET: "RESET_FORM",
};